# Generated by Django 5.2.9 on 2026-01-05 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_student_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_active',
        ),
    ]
